import { type RefObject, useEffect, useRef, useState } from 'react'
import { useMutation, useQuery } from '@tanstack/react-query'
import { Link, useOutletContext } from 'react-router-dom'
import type { GenerateResult, Topic } from '@research-portal/core'
import { ApiError, generateArtifact, getFacets } from '../api/client.ts'
import { EmptyState, ErrorCard, LiveStatus, Skeleton } from '../components/ui.tsx'
import {
  type AssessmentObject,
  AssessmentQuiz,
  isAssessment,
} from '../components/AssessmentQuiz.tsx'
import type { TenantOutletContext } from './TenantLayout.tsx'

// ---------------------------------------------------------------------------
// Self assessment - pick a knowledge area, choose the size and depth of the
// check, then take a schema-enforced quiz generated by the same machinery
// that powers Generate's "Assessment" artefact. Count and depth are not
// server-side parameters (the /generate endpoint takes a single free-text
// query), so they are folded into the instruction text sent as that query -
// the server's schema still enforces the quiz shape either way.
// ---------------------------------------------------------------------------

type QuestionCount = 3 | 5 | 10
type Depth = 'foundational' | 'intermediate' | 'advanced'

const COUNT_OPTIONS: QuestionCount[] = [3, 5, 10]

const DEPTH_OPTIONS: { id: Depth; label: string; instruction: string }[] = [
  {
    id: 'foundational',
    label: 'Foundational',
    instruction:
      'Focus on core definitions, terminology and the basic what and why - suitable for someone new to the topic.',
  },
  {
    id: 'intermediate',
    label: 'Intermediate',
    instruction:
      'Focus on how the concepts are applied in practice and how they relate to each other - suitable for someone with working knowledge.',
  },
  {
    id: 'advanced',
    label: 'Advanced',
    instruction:
      'Focus on nuanced distinctions, edge cases and trade-offs - suitable for someone with deep experience in the area.',
  },
]

const DEPTH_BY_ID = new Map(DEPTH_OPTIONS.map((d) => [d.id, d]))

function buildAssessmentQuery(topicLabel: string, count: QuestionCount, depth: Depth): string {
  const meta = DEPTH_BY_ID.get(depth) ?? DEPTH_OPTIONS[0]
  return `Quiz me on ${topicLabel}. Generate exactly ${count} multiple-choice questions at ${meta?.label.toLowerCase()} depth. ${meta?.instruction} Cover a spread of sub-topics within ${topicLabel} rather than repeating the same idea.`
}

/** A generic-looking radio group of button pills - mirrors the retrieval-mode picker on Search. */
function PillRadioGroup<T extends string | number>({
  label,
  options,
  value,
  onChange,
}: {
  label: string
  options: { id: T; label: string }[]
  value: T
  onChange: (next: T) => void
}) {
  return (
    <div role='radiogroup' aria-label={label} className='flex flex-wrap gap-2'>
      {options.map((option) => {
        const active = option.id === value
        return (
          <button
            key={String(option.id)}
            type='button'
            role='radio'
            aria-checked={active}
            onClick={() => onChange(option.id)}
            className={`rp-focus rounded-[var(--rp-radius)] border px-4 py-2 text-sm font-medium transition-colors duration-150 ${
              active
                ? 'text-[var(--rp-on-primary)]'
                : 'border-line bg-surface text-ink-2 hover:bg-[var(--rp-surface-2)] hover:text-ink'
            }`}
            style={active
              ? { backgroundColor: 'var(--rp-primary)', borderColor: 'var(--rp-primary)' }
              : undefined}
          >
            {option.label}
          </button>
        )
      })}
    </div>
  )
}

function AreaCard({
  topic,
  count,
  countLoading,
  onSelect,
}: {
  topic: Topic
  count: number | null
  countLoading: boolean
  onSelect: () => void
}) {
  return (
    <button
      type='button'
      onClick={onSelect}
      className='rp-focus rp-card group flex flex-col items-start gap-2 p-5 text-left transition-colors duration-150 hover:bg-[var(--rp-surface-2)]'
    >
      <span className='text-base font-semibold tracking-tight text-ink'>{topic.label}</span>
      {countLoading
        ? <Skeleton className='h-4 w-20' />
        : count !== null
        ? (
          <span className='text-xs font-medium uppercase tracking-wide text-ink-3'>
            {count} {count === 1 ? 'source' : 'sources'}
          </span>
        )
        : null}
      <span
        className='mt-2 inline-flex items-center gap-1 text-sm font-medium transition-transform duration-150 group-hover:translate-x-0.5'
        style={{ color: 'var(--rp-accent-fg)' }}
      >
        Build an assessment
        <svg viewBox='0 0 16 16' fill='currentColor' className='h-3.5 w-3.5' aria-hidden='true'>
          <path
            d='M6 3.5l4.5 4.5L6 12.5'
            stroke='currentColor'
            strokeWidth='1.5'
            fill='none'
            strokeLinecap='round'
            strokeLinejoin='round'
          />
        </svg>
      </span>
    </button>
  )
}

/**
 * Self assessment - "Industry Knowledge Areas" cards, a build step (question
 * count and depth), then a generated interactive quiz with a results
 * summary. Mirrors the benchmark's certification-style knowledge check,
 * built on the portal's existing schema-enforced Generate machinery.
 */
export function AssessmentPage() {
  const { config } = useOutletContext<TenantOutletContext>()
  const slug = config.slug

  const [selectedTopic, setSelectedTopic] = useState<Topic | null>(null)
  const [count, setCount] = useState<QuestionCount>(5)
  const [depth, setDepth] = useState<Depth>('intermediate')

  const { data: facets, isLoading: facetsLoading } = useQuery({
    queryKey: ['facets', slug, 'topic'],
    queryFn: () => getFacets(slug, ['topic']),
  })
  const topicCounts = facets?.topic ?? {}

  const mutation = useMutation({
    mutationFn: (vars: { query: string }) => generateArtifact(slug, 'assessment', vars.query),
  })

  const generate = (topic: Topic, nextCount: QuestionCount, nextDepth: Depth) => {
    mutation.mutate({ query: buildAssessmentQuery(topic.label, nextCount, nextDepth) })
  }

  const currentView: 'areas' | 'build' | 'results' = !selectedTopic
    ? 'areas'
    : mutation.data
    ? 'results'
    : 'build'

  const headingRef = useRef<HTMLHeadingElement>(null) as RefObject<HTMLHeadingElement>
  useEffect(() => {
    headingRef.current?.focus()
  }, [currentView])

  const chooseTopic = (topic: Topic) => {
    setSelectedTopic(topic)
    mutation.reset()
  }

  const changeArea = () => {
    setSelectedTopic(null)
    mutation.reset()
  }

  const tryAnother = () => {
    mutation.reset()
  }

  const isRateLimited = mutation.error instanceof ApiError && mutation.error.status === 429
  const errorMessage = isRateLimited
    ? 'You are asking faster than the portal can answer - please wait a moment and try again.'
    : mutation.error instanceof Error
    ? mutation.error.message
    : 'The assessment could not be generated - try again.'

  const assessmentObject = mutation.data && isAssessment(mutation.data.object)
    ? mutation.data.object
    : null

  const liveMessage = mutation.isPending
    ? `Generating your ${
      selectedTopic?.label ?? ''
    } assessment - this can take up to half a minute…`
    : mutation.isSuccess
    ? 'Assessment ready.'
    : mutation.isError
    ? errorMessage
    : ''

  return (
    <main className='mx-auto max-w-6xl px-6 py-10'>
      <LiveStatus message={liveMessage} />
      <p className='text-xs font-semibold uppercase tracking-wide text-ink-3'>Self assessment</p>
      <h1 className='mt-1 text-2xl font-semibold tracking-tight text-ink'>
        Industry Knowledge Areas
      </h1>
      <p className='mt-1 max-w-2xl text-sm text-ink-2'>
        Pick a knowledge area, choose how many questions and how deep to go, then take a generated
        knowledge check grounded in this portal's content.
      </p>

      {currentView === 'areas' && (
        <section className='mt-8'>
          <h2
            ref={headingRef}
            tabIndex={-1}
            className='text-sm font-semibold uppercase tracking-wide text-ink-3'
          >
            Choose a knowledge area
          </h2>

          {config.topics.length === 0
            ? (
              <div className='mt-4'>
                <EmptyState
                  title='No knowledge areas yet'
                  description='This portal has no topics defined yet, so there is nothing to build an assessment from. An administrator can add categories from Taxonomy, or run a corpus analysis to build the taxonomy automatically.'
                >
                  <Link to={`/t/${slug}/taxonomy`} className='rp-btn rp-btn-primary'>
                    Open taxonomy
                  </Link>
                </EmptyState>
              </div>
            )
            : (
              <div className='mt-4 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4'>
                {config.topics.map((topic) => (
                  <AreaCard
                    key={topic.id}
                    topic={topic}
                    count={topicCounts[topic.id] ?? null}
                    countLoading={facetsLoading}
                    onSelect={() => chooseTopic(topic)}
                  />
                ))}
              </div>
            )}
        </section>
      )}

      {currentView === 'build' && selectedTopic && (
        <section className='mt-8'>
          <div className='flex items-center justify-between gap-3'>
            <h2
              ref={headingRef}
              tabIndex={-1}
              className='text-lg font-semibold tracking-tight text-ink'
            >
              Build your assessment: {selectedTopic.label}
            </h2>
            <button type='button' onClick={changeArea} className='rp-btn rp-btn-ghost shrink-0'>
              Change area
            </button>
          </div>

          {!mutation.isPending && (
            <div className='rp-card mt-4 space-y-6 p-6'>
              <div>
                <p className='mb-2 text-sm font-medium text-ink'>Number of questions</p>
                <PillRadioGroup
                  label='Number of questions'
                  value={count}
                  onChange={setCount}
                  options={COUNT_OPTIONS.map((c) => ({ id: c, label: String(c) }))}
                />
              </div>

              <div>
                <p className='mb-2 text-sm font-medium text-ink'>Depth</p>
                <PillRadioGroup
                  label='Depth'
                  value={depth}
                  onChange={setDepth}
                  options={DEPTH_OPTIONS.map((d) => ({ id: d.id, label: d.label }))}
                />
              </div>

              <button
                type='button'
                onClick={() => generate(selectedTopic, count, depth)}
                className='rp-btn rp-btn-primary'
              >
                Generate assessment
              </button>
            </div>
          )}

          {mutation.isPending && (
            <div className='mt-4 animate-pulse rounded-[calc(var(--rp-radius)+4px)] border border-line bg-surface p-8'>
              <p className='text-sm font-medium text-ink'>
                Generating your {selectedTopic.label}{' '}
                assessment - this can take up to half a minute…
              </p>
              <div className='mt-5 h-4 w-1/3 rounded bg-surface-3' />
              <div className='mt-4 h-3 w-full rounded bg-surface-2' />
              <div className='mt-2 h-3 w-5/6 rounded bg-surface-2' />
              <div className='mt-2 h-3 w-2/3 rounded bg-surface-2' />
            </div>
          )}

          {mutation.isError && !mutation.isPending && (
            <div className='mt-4'>
              <ErrorCard
                message={errorMessage}
                onRetry={() => generate(selectedTopic, count, depth)}
              />
            </div>
          )}
        </section>
      )}

      {currentView === 'results' && selectedTopic && mutation.data && (
        <ResultsView
          headingRef={headingRef}
          topic={selectedTopic}
          result={mutation.data}
          assessmentObject={assessmentObject}
          onTryAnother={tryAnother}
          onChangeArea={changeArea}
        />
      )}
    </main>
  )
}

function ResultsView({
  headingRef,
  topic,
  result,
  assessmentObject,
  onTryAnother,
  onChangeArea,
}: {
  headingRef: RefObject<HTMLHeadingElement>
  topic: Topic
  result: GenerateResult
  assessmentObject: AssessmentObject | null
  onTryAnother: () => void
  onChangeArea: () => void
}) {
  return (
    <section className='mt-8'>
      <div className='flex items-center justify-between gap-3'>
        <h2
          ref={headingRef}
          tabIndex={-1}
          className='text-lg font-semibold tracking-tight text-ink'
        >
          {topic.label} knowledge check
        </h2>
        <button type='button' onClick={onChangeArea} className='rp-btn rp-btn-ghost shrink-0'>
          Change area
        </button>
      </div>

      <div className='mt-4'>
        {result.insufficientGrounding
          ? (
            <EmptyState
              title='Not enough to work with'
              description={result.message ??
                `There is not enough source material in this portal to generate a grounded assessment on ${topic.label}. Try a broader topic or check the Library for coverage.`}
            >
              <button type='button' onClick={onTryAnother} className='rp-btn rp-btn-outline'>
                Try another
              </button>
            </EmptyState>
          )
          : assessmentObject
          ? <AssessmentQuiz data={assessmentObject} onRetake={onTryAnother} />
          : (
            <div
              className='rounded-[calc(var(--rp-radius)+4px)] border p-4'
              style={{ borderColor: 'var(--rp-warn-line)', background: 'var(--rp-warn-bg)' }}
            >
              <p className='text-sm font-medium' style={{ color: 'var(--rp-warn-ink)' }}>
                This result did not match the expected quiz shape.
              </p>
              <button type='button' onClick={onTryAnother} className='rp-btn rp-btn-outline mt-3'>
                Try another
              </button>
            </div>
          )}
      </div>

      {!result.insufficientGrounding && (
        <div className='mt-6 border-t border-line pt-5'>
          <p className='text-xs font-semibold uppercase tracking-wide text-ink-3'>
            Grounded in {result.sources.length} {result.sources.length === 1 ? 'source' : 'sources'}
          </p>
          {result.sources.length > 0 && (
            <div className='mt-2 flex flex-wrap gap-2'>
              {result.sources.map((s) => (
                <span key={s.id} title={s.title} className='rp-chip max-w-[16rem] truncate'>
                  {s.title}
                </span>
              ))}
            </div>
          )}
        </div>
      )}
    </section>
  )
}
